### ISSUE TITLE
Feature request: import .txt waypoint files

### ISSUE THREAD

**Issue by mutatron** [DroidPlanner/Tower#1508] opened 2015-07-06 05:36 UTC
I don't really care if Tower exports to .txt, but it would be useful to import .txt files created in Mission Planner or APM. It can't be that hard, and it would make Tower much more useful. I prefer to create missions in the desktop software because it's easier and more flexible.

**Comment by Thalek** [comment] 2015-07-06 05:55
Might as well add the capability of exporting to text; not only would much of the programming already be accomplished for the importing of text, but having human-readable files would have some applications too.

**Comment by squilter** [comment] 2015-07-06 18:36
This is a duplicate of #1482.  I will look into the issue soon.

**Closed by squilter** 2015-07-06 18:36 UTC
