### ISSUE TITLE
Save survey dialog settings

### ISSUE THREAD

**Issue by BitMapping** [DroidPlanner/Tower#1448] opened 2015-03-21 21:32 UTC
It would be a very comfortable if the last settings in the survey dialog would be automatically saved. Normally, apart from the hatch angle, one does not change the cameras and the general mission parameters (overlays, altitude, ...) too often.

**Comment by SciAero** [comment] 2015-10-28 11:49
Agree that the survey camera and overlap settings should be remembered, or alternatively be able to change the default values in the settings.

**Comment by ne0fhyk** [comment] 2016-08-17 17:30
Duplicate of #1776. Will be addressed for version 4.0

**Closed by ne0fhyk** 2016-08-17 17:30 UTC
