### ISSUE TITLE
Add functionality to cancel ROI and resume heading in direction of travel

### ISSUE THREAD

**Issue by idleup** [DroidPlanner/Tower#1428] opened 2015-03-06 22:22 UTC
Currently it will face the ROI until either the mission is completed or you define another ROI. There are times you along want to face an ROI between specific waypoints and then the duration of the mission have it face direction of travel. I have not found a way to do this currently.

**Comment by PaulLoizeaux** [comment] 2015-03-09 22:33
To reset the ROI to the direction of travel just insert a second ROI at the point you want it to revert to normal and have Lat, Lon, and Alt be 0.

Source: http://copter.ardupilot.com/wiki/mission-planning-and-analysis/mission-command-list/#do-set-roi

**Comment by Thalek** [comment] 2015-03-09 22:42
Sounds rather non-intuitive, to me.

**Comment by ne0fhyk** [comment] 2015-03-09 22:55
@Thalek the plan is to add a 'cancel ROI mode' to the ROI waypoint, that will hide/abstract the reset mechanism.

**Comment by Thalek** [comment] 2015-03-10 00:12
Ahhhh.  Sounds good.

**Comment by ne0fhyk** [comment] 2015-09-26 23:18
duplicate of #1267

**Closed by ne0fhyk** 2015-09-26 23:18 UTC
