### ISSUE TITLE
tower get crazy with pixhawk-storm32 combo 

### ISSUE THREAD

**Issue by lijingwei0710** [DroidPlanner/Tower#1493] opened 2015-06-02 07:27 UTC
watch the video for the issue:
https://www.youtube.com/watch?v=KzHd5ndXE84

And from Olliw:
this I think is neither an issue of the STorM32 nor the pixhawk, but the ground control software ... I guess believe the issue is that it can't handle having two heartbeats from two systems coming in (Mission Planner e.g. handles this well) 
a similar "surprise" occurred with the Frsky telemetry...

with the addition of the StorM32 we are moving from a monoculture to an ecosystem, but mavlink isn't really able to handle that well, and moreover many peripherals seem not yet up to that at all 

I guess the only option is to talk to the ground control software folks

**Comment by squilter** [comment] 2015-07-06 19:55
This is a duplicate of #1481

**Closed by squilter** 2015-07-06 19:55 UTC
