### ISSUE TITLE
Manually entering decimal values in change speed 

### ISSUE THREAD

**Issue by joeynuggetz** [DroidPlanner/Tower#1660] opened 2015-10-21 19:47 UTC
. If you manually enter a speed of 2.0 and hit enter the slider moves to 20. Entering 2.5 moves slider to 25, etc.  Nevermind, looks like behavior is not present in 3.2.1 beta 1

**Comment by ne0fhyk** [comment] 2015-10-21 19:54
@joeynuggetz Thanks for the bug report. This is a duplicate of issue #1633 , and the issue has been fixed.
It's available for testing in [Tower v3.2.1 Beta 1](https://play.google.com/apps/testing/org.droidplanner.android.beta).

**Closed by ne0fhyk** 2015-10-21 19:54 UTC
