### ISSUE TITLE
Downlaod Dataflash Log via Mavlink

### ISSUE THREAD

**Issue by j0nson** [DroidPlanner/Tower#1554] opened 2015-07-31 18:00 UTC
Please add the ability to download Dataflash logs.  It has been available over mavlink since apm copter 3.2 .  Ideally, this file would be uploaded to droneshare instead of the telemetry log, for more accurate logging and analysis.

**Comment by ne0fhyk** [comment] 2015-07-31 20:19
Closing as this is a duplicate of #1335

**Closed by ne0fhyk** 2015-07-31 20:19 UTC
