### ISSUE TITLE
Tower crashes when connecting other ground stations

### ISSUE THREAD

**Issue by benjanisa** [DroidPlanner/Tower#1809] opened 2016-09-12 13:03 UTC
Hi

We are having issues where Tower is crashing whenever we connect another ground station. We are connecting a Raspberry Pi to trigger our camera system, however as soon as the Pi is connected Tower crashes. 

We have noticed the System ID of the pixhawk seems to change on Tower as soon as the Pi is connected (it gets set to 1, but on connecting the Pi it changes to -4 for some reason). 

Any ideas!?

**Comment by ne0fhyk** [comment] 2016-09-21 18:07
Seems to be a duplicate of https://github.com/DroidPlanner/Tower/issues/1733

**Closed by ne0fhyk** 2016-09-21 18:07 UTC
