### ISSUE TITLE
Tower and antenna tracker.

### ISSUE THREAD

**Issue by visper1** [DroidPlanner/Tower#1640] opened 2015-10-11 08:26 UTC
Hello, I have a little problem with the Tower application. With my copter works very well. But when I connect APM antenna tracker, so they are Mavlink two devices. Mission Planner with no problem, each device transmits its SYSID and MP asks which want to control. Tower but it can not and displays together two SYSID and making mismatch. I do not need to control the antenna tracker through the Tower, but I need to be tracker SYSID ignored.

**Comment by rmackay9** [comment] 2015-10-11 14:01
I think this is a duplicate of this issue I already raised: https://github.com/DroidPlanner/Tower/issues/1481

**Comment by visper1** [comment] 2015-10-11 15:19
Yes, this is the same problem. Tower have problem with multiple devices on Mavlink. Mission planner have "sysid selector".
![sysid selector](https://cloud.githubusercontent.com/assets/15064218/10417445/2d60c83e-703c-11e5-9bcf-d4279354db53.jpg)

**Comment by ne0fhyk** [comment] 2015-10-11 16:59
@visper1 I'm closing this issue since it's a duplicate of #1481 as @rmackay9 pointed out.
Let's continue the conversation there!

**Closed by ne0fhyk** 2015-10-11 16:59 UTC
